---
title: "Bitcoin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, echo=TRUE, message=FALSE, warning=FALSE}
#cargamos las librerías
library(ggplot2)
library(dplyr)
library(caret)
```


```{r, echo=TRUE, message=FALSE, warning=FALSE}

bitcoin <- read.csv("BitcoinHeistData.csv")

head(bitcoin)

summary(bitcoin)
```
```{r, echo=TRUE, message=FALSE, warning=FALSE}
bitcoin%>%
  group_by(label)%>%
  count()
```

There are 3 families of Rasomware: Montreal, Padua and Princeton that we are going to group in a label "rasomware" to treat this problem as binary classfication


```{r, echo=TRUE, message=FALSE, warning=FALSE}
bitcoin <- bitcoin%>%
  mutate(b_label = if_else(label== "white", "noRasomware", "Rasomware"))

```

## EDA

```{r, echo=TRUE, message=FALSE, warning=FALSE}

bitcoin %>%
  group_by(b_label) %>%
  count()


ggplot(data = bitcoin, aes(x=b_label, fill= b_label)) + geom_bar(stat = 'count') 
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
sum(is.na(bitcoin))


ggplot(data = bitcoin, aes (x=weight, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
ggplot(data = bitcoin, aes (x=length, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
ggplot(data = bitcoin, aes (x=count, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
ggplot(data = bitcoin, aes (x=looped, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
ggplot(data = bitcoin, aes (x=neighbors, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
ggplot(bitcoin) + aes(x = b_label, y = income, color=b_label) + geom_jitter()

```


Transforming day of year into dates

```{r echo=TRUE, message=FALSE, warning=FALSE}


bitcoin$ref_date <- paste(as.character(bitcoin$year-1),"-12-31", sep="")

bitcoin$new_date <- as.Date(bitcoin$day, origin= bitcoin$ref_date)


ggplot(data = bitcoin, aes(x=new_date, y= income)) + geom_line() 

```

### Outliers

Boxplots of some variables shown the presence of outliers

```{r echo=TRUE, message=FALSE, warning=FALSE}
#removing outliers in weight
weight_out <- boxplot(bitcoin$weight, plot = FALSE)$out

new_bitcoin <- bitcoin
new_bitcoin <- new_bitcoin[-which(new_bitcoin$weight %in% weight_out),]

ggplot(data = new_bitcoin, aes (x=weight, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
``` 


```{r, echo=TRUE, message=FALSE, warning=FALSE}

#remove neighbors outliers

neigh_out <- boxplot(bitcoin$neighbors, plot=FALSE)$out

new_bitcoin <- new_bitcoin[-which(new_bitcoin$neighbors %in% neigh_out),]

ggplot(data = new_bitcoin, aes (x=neighbors, color=b_label)) + geom_boxplot() + facet_wrap(~b_label)
```

### Correlation

```{r, echo=TRUE, message=FALSE, warning=FALSE}
new_bitcoin$new_label <- if_else(new_bitcoin$b_label == 'Rasomware', 1, 0)
cor(new_bitcoin[c("length", "weight", "count", "looped", "neighbors", "income")])

```
### Normalization

```{r, echo=TRUE, message=FALSE, warning=FALSE}
par(mfcol=c(2,1))
hist(new_bitcoin$income)
hist(log(new_bitcoin$income))

```

```{r, echo=TRUE, message=FALSE, warning=FALSE}

par(mfcol = c(2,1))
hist(new_bitcoin$length)
hist(log(new_bitcoin$length))
```
```{r, echo=TRUE, message=FALSE, warning=FALSE}

par(mfcol = c(2,1))
hist(new_bitcoin$weight)
hist(log(new_bitcoin$weight))
```
```{r, echo=TRUE, message=FALSE, warning=FALSE}

par(mfcol = c(2, 1))
hist(new_bitcoin$neighbors)
hist(log(new_bitcoin$neighbors))

```

## SVM


```{r, echo=TRUE, message=FALSE, warning=FALSE}
#https://github.com/dataprofessor/code/blob/master/iris/iris-classification.R

normalize <- function(x){
  return((x-min(x))/(max(x)-min(x)))
}

df <- new_bitcoin[c("length", "weight", "count", "looped", "neighbors", "income", "new_label")]

df$income <- log(df$income)

df$length <- normalize(df$length)
df$weight <- normalize(df$weight)
df$count <- normalize(df$count)
df$looped <- normalize(df$looped)
df$neighbors <- normalize(df$neighbors)
df$income <- normalize(df$income)

set.seed(100)
train_index <- createDataPartition(df$new_label, p=0.7, list = FALSE)

train_df <- df[train_index,]
test_df <- df[-train_index,]


svm_model <- train(new_label ~ ., data = train_df,  method = "svmLinear",
  trControl = trainControl("cv", number = 10)
  )
```



